"""`bh` installation contract — A2 §35.

Installs a tiny POSIX-sh shim to ~/.local/bin/bh and records the repo root and
project interpreter under the support dir. The shim resolves everything from
absolute state, so it runs identically from any cwd and under launchd
(A2 §35.4). Install is idempotent and re-runnable (A2 §35.7).
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

from . import paths

# The shim is deliberately dependency-free POSIX sh. It reads only absolute
# state (support-dir files, $HOME) — never a login profile, never $PATH for the
# interpreter — so a launchd agent behaves exactly like an interactive shell.
_SHIM = """#!/bin/sh
# bh — Bristow-Hall operations shim (generated by `python3 -m bh install`).
# Do not edit by hand; re-run `bh doctor --fix-install` to regenerate.
set -eu
SUPPORT="$HOME/Library/Application Support/bristow-hall"
BH_REPO="${BH_REPO:-}"
if [ -z "$BH_REPO" ] && [ -f "$SUPPORT/repo.path" ]; then
  BH_REPO="$(cat "$SUPPORT/repo.path")"
fi
if [ -z "$BH_REPO" ] || [ ! -d "$BH_REPO/live_data" ]; then
  echo "bh: repo not resolved (set BH_REPO or write $SUPPORT/repo.path)" >&2
  exit 78
fi
INTERP=""
if [ -f "$SUPPORT/interpreter.path" ]; then
  INTERP="$(cat "$SUPPORT/interpreter.path")"
fi
if [ -z "$INTERP" ] || [ ! -x "$INTERP" ]; then
  echo "bh: interpreter not resolved (run: python3 -m bh install)" >&2
  exit 78
fi
export BH_REPO
export PYTHONPATH="$BH_REPO${PYTHONPATH:+:$PYTHONPATH}"
exec "$INTERP" -B -m bh "$@"
"""


def _atomic_write(path: Path, text: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / (path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def install(repo: Path | None = None) -> dict:
    """Write the shim + support-dir config. Idempotent (A2 §35.7).

    Returns a report dict (no secrets). Records sys.executable — the interpreter
    that ran this install — as the project interpreter (A2 §35.3).
    """
    # Bootstrap: on first install neither $BH_REPO nor repo.path exists yet, so
    # seed the root from this package's own absolute location (bh/..). This is
    # the package file location, not an assumed cwd (A2 §35.2).
    if repo is not None:
        root = paths.resolve_repo(str(repo))
    else:
        try:
            root = paths.resolve_repo()
        except paths.ResolutionError:
            pkg_root = Path(__file__).resolve().parents[1]
            if not ((pkg_root / "live_data").is_dir() and (pkg_root / "data_vault").is_dir()):
                raise
            root = pkg_root
    support = paths.support_dir()
    support.mkdir(parents=True, exist_ok=True)

    _atomic_write(support / "repo.path", str(root) + "\n", 0o644)
    _atomic_write(support / "interpreter.path", sys.executable + "\n", 0o644)

    shim = paths.bh_bin_path()
    _atomic_write(shim, _SHIM, 0o755)
    # Belt-and-suspenders: ensure the exec bit survived the atomic replace.
    os.chmod(shim, os.stat(shim).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return {
        "shim": str(shim),
        "repo_path_file": str(support / "repo.path"),
        "interpreter_path_file": str(support / "interpreter.path"),
        "repo": str(root),
        "interpreter": sys.executable,
        "idempotent": True,
    }
