#!/usr/bin/env python3
"""Build a machine-readable catalog for every locally represented series.

The catalog deliberately separates observed facts from inferred metadata.  A
series identifier, local byte coverage, and retained vintage count are
observed.  Publisher/category/frequency values generated by rules are labeled
as such and remain subject to source-specific review.
"""

from __future__ import annotations

import argparse
import ast
import csv
import json
import re
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Set, Tuple


SCHEMA_VERSION = "recession-monitor-v2.metric-catalog.v1"

FIELDS = (
    "schema_version",
    "series_id",
    "title",
    "category",
    "publisher",
    "provider",
    "provider_series_id",
    "provider_landing_url",
    "observation_frequency",
    "frequency_evidence",
    "units",
    "seasonal_adjustment",
    "local_first_observation",
    "local_last_observation",
    "local_1950_coverage_status",
    "local_file_count",
    "local_current_file_count",
    "local_vintage_file_count",
    "local_first_vintage",
    "local_last_vintage",
    "local_lanes_json",
    "parse_statuses_json",
    "original_production_input",
    "task3_governed_input",
    "forecast_or_nowcast",
    "revision_class",
    "named_vintage_local_status",
    "strict_first_release_local_status",
    "release_clock_status",
    "rights_status",
    "metadata_confidence",
    "notes",
)


# Curated labels cover the original inputs and the principal expansion,
# severity, falsification, financial, and forecast families.  Unlisted local
# identifiers remain in the catalog under their exact identifier.
CURATED: Mapping[str, Mapping[str, str]] = {
    "CPFF": {"title": "3-Month Commercial Paper Minus Federal Funds Rate", "category": "short_term_funding_spread", "publisher": "st-louis-fed", "frequency": "daily", "units": "percent"},
    "M2REAL": {"title": "Real M2 Money Stock", "category": "money_supply", "publisher": "st-louis-fed", "frequency": "monthly", "units": "billions_of_1982_1984_dollars"},
    "NFCICREDIT": {"title": "Chicago Fed NFCI Credit Subindex", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly", "units": "index"},
    "NFCILEVERAGE": {"title": "Chicago Fed NFCI Leverage Subindex", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly", "units": "index"},
    "NFCIRISK": {"title": "Chicago Fed NFCI Risk Subindex", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly", "units": "index"},
    "T5YIFR": {"title": "5-Year, 5-Year Forward Inflation Expectation Rate", "category": "inflation_expectations", "publisher": "st-louis-fed", "frequency": "daily", "units": "percent"},
    "TRUCKD11": {"title": "Truck Tonnage Index", "category": "freight_activity", "publisher": "bts", "frequency": "monthly", "units": "index_2015_100"},
    "A229RX0": {"title": "Real disposable personal income: per capita", "category": "income", "publisher": "bea", "frequency": "monthly"},
    "AAA": {"title": "Moody's seasoned Aaa corporate bond yield", "category": "credit", "publisher": "moodys", "frequency": "monthly", "units": "percent"},
    "AAA10Y": {"title": "Moody's Aaa less 10-year Treasury spread", "category": "credit", "publisher": "moodys", "frequency": "daily", "units": "percentage_points"},
    "ADS_INDEX": {"title": "Aruoba-Diebold-Scotti business conditions index", "category": "composite_activity", "publisher": "philadelphia-fed", "frequency": "daily"},
    "AHETPI": {"title": "Average hourly earnings of production and nonsupervisory employees", "category": "labor_income", "publisher": "bls", "frequency": "monthly"},
    "AMTMNO": {"title": "Manufacturers' total new orders", "category": "orders", "publisher": "census", "frequency": "monthly"},
    "ANFCI": {"title": "Adjusted National Financial Conditions Index", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly"},
    "AWHMAN": {"title": "Average weekly hours, manufacturing", "category": "labor_hours", "publisher": "bls", "frequency": "monthly"},
    "AWHNONAG": {"title": "Average weekly hours, private nonagricultural", "category": "labor_hours", "publisher": "bls", "frequency": "monthly"},
    "AWOTMAN": {"title": "Average weekly overtime hours, manufacturing", "category": "labor_hours", "publisher": "bls", "frequency": "monthly"},
    "BAA": {"title": "Moody's seasoned Baa corporate bond yield", "category": "credit", "publisher": "moodys", "frequency": "monthly", "units": "percent"},
    "BAA10Y": {"title": "Moody's Baa less 10-year Treasury spread", "category": "credit", "publisher": "moodys", "frequency": "daily", "units": "percentage_points"},
    "BAMLC0A0CM": {"title": "ICE BofA US corporate option-adjusted spread", "category": "credit", "publisher": "ice-bofa", "frequency": "daily"},
    "BAMLH0A0HYM2": {"title": "ICE BofA US high-yield option-adjusted spread", "category": "credit", "publisher": "ice-bofa", "frequency": "daily"},
    "BAMLH0A0HYM2EY": {"title": "ICE BofA US high-yield effective yield", "category": "credit", "publisher": "ice-bofa", "frequency": "daily"},
    "BUSLOANS": {"title": "Commercial and industrial loans at commercial banks", "category": "bank_credit", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "CC4WSA": {"title": "Four-week moving average of continued claims", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "CCLACBW027SBOG": {"title": "Consumer loans at all commercial banks", "category": "bank_credit", "publisher": "federal-reserve-board", "frequency": "weekly"},
    "CCSA": {"title": "Continued claims, seasonally adjusted", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "CE16OV": {"title": "Civilian employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "CFNAI": {"title": "Chicago Fed National Activity Index", "category": "composite_activity", "publisher": "chicago-fed", "frequency": "monthly"},
    "CFNAIDIFF": {"title": "CFNAI diffusion index", "category": "composite_activity", "publisher": "chicago-fed", "frequency": "monthly"},
    "CFNAIMA3": {"title": "CFNAI three-month moving average", "category": "composite_activity", "publisher": "chicago-fed", "frequency": "monthly"},
    "CIVPART": {"title": "Civilian labor-force participation rate", "category": "labor_supply", "publisher": "bls", "frequency": "monthly"},
    "CLEVELAND_INFLATION_NOWCAST_Q": {"title": "Cleveland Fed inflation nowcast", "category": "forecast", "publisher": "cleveland-fed", "frequency": "daily"},
    "CLF16OV": {"title": "Civilian labor force", "category": "labor_supply", "publisher": "bls", "frequency": "monthly"},
    "CMDEBT": {"title": "Household and nonprofit debt securities and loans", "category": "credit", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "CMRMTSPL": {"title": "Real manufacturing and trade industries sales", "category": "real_activity", "publisher": "st-louis-fed", "frequency": "monthly"},
    "CNP16OV": {"title": "Civilian noninstitutional population", "category": "demography", "publisher": "bls", "frequency": "monthly"},
    "CPIAUCSL": {"title": "Consumer Price Index for all urban consumers", "category": "prices", "publisher": "bls", "frequency": "monthly"},
    "CPILFESL": {"title": "Consumer Price Index excluding food and energy", "category": "prices", "publisher": "bls", "frequency": "monthly"},
    "CSUSHPINSA": {"title": "S&P CoreLogic Case-Shiller US home price index", "category": "housing_prices", "publisher": "sp-corelogic", "frequency": "monthly"},
    "CUMFNS": {"title": "Manufacturing capacity utilization", "category": "production", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "DAAA": {"title": "Moody's Aaa corporate bond yield", "category": "credit", "publisher": "moodys", "frequency": "daily"},
    "DBAA": {"title": "Moody's Baa corporate bond yield", "category": "credit", "publisher": "moodys", "frequency": "daily"},
    "DCOILBRENTEU": {"title": "Brent crude oil spot price", "category": "energy", "publisher": "eia", "frequency": "daily"},
    "DCOILWTICO": {"title": "West Texas Intermediate crude oil spot price", "category": "energy", "publisher": "eia", "frequency": "daily"},
    "DEXCAUS": {"title": "Canada/US foreign exchange rate", "category": "foreign_exchange", "publisher": "federal-reserve-board", "frequency": "daily"},
    "DEXJPUS": {"title": "Japan/US foreign exchange rate", "category": "foreign_exchange", "publisher": "federal-reserve-board", "frequency": "daily"},
    "DEXUSEU": {"title": "US/euro foreign exchange rate", "category": "foreign_exchange", "publisher": "federal-reserve-board", "frequency": "daily"},
    "DEXUSUK": {"title": "US/UK foreign exchange rate", "category": "foreign_exchange", "publisher": "federal-reserve-board", "frequency": "daily"},
    "DFF": {"title": "Effective federal funds rate", "category": "monetary_policy", "publisher": "federal-reserve-bank-of-new-york", "frequency": "daily"},
    "DGORDER": {"title": "Manufacturers' durable goods orders", "category": "orders", "publisher": "census", "frequency": "monthly"},
    "DGS1": {"title": "1-year Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "daily"},
    "DGS10": {"title": "10-year Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "daily"},
    "DGS2": {"title": "2-year Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "daily"},
    "DGS3MO": {"title": "3-month Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "daily"},
    "DHHNGSP": {"title": "Henry Hub natural gas spot price", "category": "energy", "publisher": "eia", "frequency": "daily"},
    "DJIA": {"title": "Dow Jones Industrial Average", "category": "equity_market", "publisher": "sp-dow-jones", "frequency": "daily"},
    "DRTSCILM": {"title": "Senior Loan Officer Survey: tightening C&I standards", "category": "credit_conditions", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "DSPIC96": {"title": "Real disposable personal income", "category": "income", "publisher": "bea", "frequency": "monthly"},
    "DTB3": {"title": "3-month Treasury bill secondary market rate", "category": "interest_rates", "publisher": "federal-reserve-board", "frequency": "daily"},
    "DTWEXBGS": {"title": "Nominal broad US dollar index", "category": "foreign_exchange", "publisher": "federal-reserve-board", "frequency": "daily"},
    "EMRATIO": {"title": "Employment-population ratio", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "FEDFUNDS": {"title": "Effective federal funds rate", "category": "monetary_policy", "publisher": "federal-reserve-bank-of-new-york", "frequency": "monthly"},
    "FEDTARMD": {"title": "SEP median federal funds rate projection", "category": "forecast", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "FEDTARMDLR": {"title": "SEP median longer-run federal funds rate", "category": "forecast", "publisher": "federal-reserve-board", "frequency": "event"},
    "GACDFSA066MSFRBPHI": {"title": "Philadelphia Fed coincident economic activity index, US", "category": "composite_activity", "publisher": "philadelphia-fed", "frequency": "monthly"},
    "GASDESW": {"title": "US on-highway diesel fuel price", "category": "energy", "publisher": "eia", "frequency": "weekly"},
    "GASREGW": {"title": "US regular gasoline price", "category": "energy", "publisher": "eia", "frequency": "weekly"},
    "GDPC1": {"title": "Real gross domestic product", "category": "real_activity", "publisher": "bea", "frequency": "quarterly"},
    "GDPC1MD": {"title": "SEP median real GDP growth projection", "category": "forecast", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "GDPC1MDLR": {"title": "SEP longer-run real GDP growth projection", "category": "forecast", "publisher": "federal-reserve-board", "frequency": "event"},
    "GDPDEF": {"title": "Gross domestic product implicit price deflator", "category": "prices", "publisher": "bea", "frequency": "quarterly"},
    "GDPNOW": {"title": "Atlanta Fed GDPNow real GDP nowcast", "category": "forecast", "publisher": "atlanta-fed", "frequency": "event"},
    "GDPPOT": {"title": "Real potential GDP", "category": "potential_output", "publisher": "cbo", "frequency": "quarterly"},
    "GFDEBTN": {"title": "Federal debt held by the public", "category": "fiscal", "publisher": "us-treasury", "frequency": "quarterly"},
    "GNPC96": {"title": "Real gross national product", "category": "real_activity", "publisher": "bea", "frequency": "quarterly"},
    "GPDIC1": {"title": "Real gross private domestic investment", "category": "investment", "publisher": "bea", "frequency": "quarterly"},
    "GS1": {"title": "1-year Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "monthly"},
    "GS10": {"title": "10-year Treasury constant maturity rate", "category": "interest_rates", "publisher": "us-treasury", "frequency": "monthly"},
    "HOUST": {"title": "Housing starts", "category": "housing", "publisher": "census", "frequency": "monthly"},
    "HTRUCKSSAAR": {"title": "Heavy-weight truck sales", "category": "transportation", "publisher": "bea", "frequency": "monthly"},
    "IC4WSA": {"title": "Four-week moving average of initial claims", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "ICNSA": {"title": "Initial claims, not seasonally adjusted", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "ICSA": {"title": "Initial claims, seasonally adjusted", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "IHLIDXUS": {"title": "Indeed job postings index", "category": "online_labor", "publisher": "indeed", "frequency": "daily"},
    "INDPRO": {"title": "Industrial production index", "category": "production", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "ISRATIO": {"title": "Manufacturing and trade inventories-to-sales ratio", "category": "inventories", "publisher": "census", "frequency": "monthly"},
    "IURSA": {"title": "Insured unemployment rate", "category": "labor_claims", "publisher": "dol-eta", "frequency": "weekly"},
    "JTSHIR": {"title": "JOLTS hires rate", "category": "labor_flows", "publisher": "bls", "frequency": "monthly"},
    "JTSJOL": {"title": "JOLTS job openings", "category": "labor_flows", "publisher": "bls", "frequency": "monthly"},
    "JTSJOR": {"title": "JOLTS job openings rate", "category": "labor_flows", "publisher": "bls", "frequency": "monthly"},
    "JTSQUR": {"title": "JOLTS quits rate", "category": "labor_flows", "publisher": "bls", "frequency": "monthly"},
    "M1SL": {"title": "M1 money stock", "category": "money", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "M2SL": {"title": "M2 money stock", "category": "money", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "MANEMP": {"title": "Manufacturing employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "MORTGAGE30US": {"title": "30-year fixed-rate mortgage average", "category": "housing_finance", "publisher": "freddie-mac", "frequency": "weekly"},
    "MSACSR": {"title": "Months' supply of new houses", "category": "housing", "publisher": "census", "frequency": "monthly"},
    "NASDAQCOM": {"title": "NASDAQ Composite Index", "category": "equity_market", "publisher": "nasdaq", "frequency": "daily"},
    "NCBDBIQ027S": {"title": "Nonfinancial corporate debt securities", "category": "credit", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "NEWORDER": {"title": "Manufacturers' new orders for durable goods", "category": "orders", "publisher": "census", "frequency": "monthly"},
    "NFCI": {"title": "National Financial Conditions Index", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly"},
    "NFCINONFINLEVERAGE": {"title": "NFCI nonfinancial leverage subindex", "category": "financial_conditions", "publisher": "chicago-fed", "frequency": "weekly"},
    "NONREVSL": {"title": "Nonrevolving consumer credit", "category": "consumer_credit", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "NROU": {"title": "Noncyclical rate of unemployment", "category": "potential_output", "publisher": "cbo", "frequency": "quarterly"},
    "OPHNFB": {"title": "Nonfarm business output per hour", "category": "productivity", "publisher": "bls", "frequency": "quarterly"},
    "PAYEMS": {"title": "Total nonfarm payroll employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "PCE": {"title": "Personal consumption expenditures", "category": "consumption", "publisher": "bea", "frequency": "monthly"},
    "PCEC96": {"title": "Real personal consumption expenditures", "category": "consumption", "publisher": "bea", "frequency": "monthly"},
    "PCECC96": {"title": "Real personal consumption expenditures", "category": "consumption", "publisher": "bea", "frequency": "quarterly"},
    "PCEPI": {"title": "Personal consumption expenditures price index", "category": "prices", "publisher": "bea", "frequency": "monthly"},
    "PERMIT": {"title": "New private housing units authorized by permits", "category": "housing", "publisher": "census", "frequency": "monthly"},
    "PPIACO": {"title": "Producer Price Index: all commodities", "category": "prices", "publisher": "bls", "frequency": "monthly"},
    "PRFI": {"title": "Private residential fixed investment", "category": "housing", "publisher": "bea", "frequency": "quarterly"},
    "PRS85006092": {"title": "Nonfarm business labor productivity", "category": "productivity", "publisher": "bls", "frequency": "quarterly"},
    "PSAVERT": {"title": "Personal saving rate", "category": "household_balance_sheet", "publisher": "bea", "frequency": "monthly"},
    "RAILFRTCARLOADSD11": {"title": "Rail freight carloads", "category": "transportation", "publisher": "association-of-american-railroads", "frequency": "monthly"},
    "RECPROUSM156N": {"title": "Chauvet-Piger smoothed recession probability", "category": "reference_model", "publisher": "jeremy-piger", "frequency": "monthly"},
    "REVOLSL": {"title": "Revolving consumer credit", "category": "consumer_credit", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "RRSFS": {"title": "Real retail and food services sales", "category": "consumption", "publisher": "census", "frequency": "monthly"},
    "RSAFS": {"title": "Retail and food services sales", "category": "consumption", "publisher": "census", "frequency": "monthly"},
    "SAHMCURRENT": {"title": "Sahm Rule indicator using current vintage unemployment", "category": "reference_model", "publisher": "fred", "frequency": "monthly"},
    "SAHMREALTIME": {"title": "Sahm Rule real-time indicator", "category": "reference_model", "publisher": "fred", "frequency": "monthly"},
    "SP500": {"title": "S&P 500 Index", "category": "equity_market", "publisher": "sp-dow-jones", "frequency": "daily"},
    "SPF_MEDIAN_RGDP_LEVEL": {"title": "SPF median real GDP level forecast", "category": "forecast", "publisher": "philadelphia-fed", "frequency": "quarterly"},
    "SPF_MEDIAN_UNEMP_LEVEL": {"title": "SPF median unemployment-rate forecast", "category": "forecast", "publisher": "philadelphia-fed", "frequency": "quarterly"},
    "SPCS20RSA": {"title": "S&P CoreLogic Case-Shiller 20-city home price index", "category": "housing_prices", "publisher": "sp-corelogic", "frequency": "monthly"},
    "STLFSI4": {"title": "St. Louis Fed Financial Stress Index", "category": "financial_conditions", "publisher": "st-louis-fed", "frequency": "weekly"},
    "T10Y2Y": {"title": "10-year less 2-year Treasury spread", "category": "yield_curve", "publisher": "federal-reserve-board", "frequency": "daily"},
    "T10Y3M": {"title": "10-year less 3-month Treasury spread", "category": "yield_curve", "publisher": "federal-reserve-board", "frequency": "daily"},
    "T10YFF": {"title": "10-year Treasury less federal funds rate", "category": "yield_curve", "publisher": "federal-reserve-board", "frequency": "daily"},
    "TB3MS": {"title": "3-month Treasury bill secondary-market rate", "category": "interest_rates", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "TBSDODNS": {"title": "Nonfinancial business debt securities and loans", "category": "credit", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "TCMDO": {"title": "All-sector debt securities and loans", "category": "credit", "publisher": "federal-reserve-board", "frequency": "quarterly"},
    "TCU": {"title": "Total industry capacity utilization", "category": "production", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "TEMPHELPS": {"title": "Temporary help services employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "TOTALSA": {"title": "Total vehicle sales", "category": "consumption", "publisher": "bea", "frequency": "monthly"},
    "TOTALSL": {"title": "Total consumer credit", "category": "consumer_credit", "publisher": "federal-reserve-board", "frequency": "monthly"},
    "TOTBKCR": {"title": "Bank credit at all commercial banks", "category": "bank_credit", "publisher": "federal-reserve-board", "frequency": "weekly"},
    "TOTLL": {"title": "Loans and leases in bank credit", "category": "bank_credit", "publisher": "federal-reserve-board", "frequency": "weekly"},
    "U6RATE": {"title": "U-6 labor underutilization rate", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UEMP15T26": {"title": "Unemployed 15 to 26 weeks", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UEMP27OV": {"title": "Unemployed 27 weeks and over", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UEMPMEAN": {"title": "Average duration of unemployment", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UEMPMED": {"title": "Median duration of unemployment", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UMCSENT": {"title": "University of Michigan consumer sentiment", "category": "sentiment", "publisher": "university-of-michigan", "frequency": "monthly"},
    "UNEMPLOY": {"title": "Unemployment level", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "UNRATE": {"title": "Civilian unemployment rate", "category": "labor_unemployment", "publisher": "bls", "frequency": "monthly"},
    "USCONS": {"title": "Construction employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USEPUINDXD": {"title": "US economic policy uncertainty index", "category": "uncertainty", "publisher": "policyuncertainty-com", "frequency": "daily"},
    "USFIRE": {"title": "Financial activities employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USINFO": {"title": "Information employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USLAH": {"title": "Leisure and hospitality employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USMINE": {"title": "Mining and logging employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USPBS": {"title": "Professional and business services employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USSERV": {"title": "Private service-providing employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USTPU": {"title": "Trade, transportation, and utilities employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USTRADE": {"title": "Retail trade employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "USWTRADE": {"title": "Wholesale trade employment", "category": "labor_employment", "publisher": "bls", "frequency": "monthly"},
    "VIXCLS": {"title": "CBOE Volatility Index", "category": "market_volatility", "publisher": "cboe", "frequency": "daily"},
    "VXOCLS": {"title": "CBOE S&P 100 volatility index", "category": "market_volatility", "publisher": "cboe", "frequency": "daily"},
    "W875RX1": {"title": "Real personal income excluding current transfers", "category": "income", "publisher": "bea", "frequency": "monthly"},
    "WALCL": {"title": "Federal Reserve total assets", "category": "central_bank_balance_sheet", "publisher": "federal-reserve-board", "frequency": "weekly"},
    "WEI": {"title": "Weekly Economic Index", "category": "composite_activity", "publisher": "federal-reserve-bank-of-new-york", "frequency": "weekly"},
    "WLEMUINDXD": {"title": "Equity market uncertainty index", "category": "uncertainty", "publisher": "policyuncertainty-com", "frequency": "daily"},
    "WTISPLC": {"title": "West Texas Intermediate crude oil price", "category": "energy", "publisher": "eia", "frequency": "monthly"},
    "anxious_index": {"title": "SPF Anxious Index", "category": "forecast", "publisher": "philadelphia-fed", "frequency": "quarterly"},
    "fdic_failures_by_year": {
        "title": "FDIC-insured bank failures by year",
        "category": "banking_stress",
        "publisher": "fdic",
        "frequency": "annual",
        "units": "failures_count_and_assets_thousands_of_us_dollars",
        "notes": (
            "assets column is the sum of FDIC API QBFASSET; FDIC BankFind "
            "defines QBFASSET and displayed Total Asset values as thousands of US dollars"
        ),
    },
    "nyfed_recession_prob": {
        "title": "Locally derived 12-month yield-curve recession probability",
        "category": "forecast",
        "publisher": "bristow-hall-local-derivation",
        "frequency": "monthly",
        "units": "probability_0_to_1",
        "rights_status": "locally_derived_from_public_inputs_with_attribution",
        "notes": (
            "local probit from GS10 minus bond-equivalent 3-month Treasury with "
            "NBER target; not the New York Fed published series; current-revised comparator only"
        ),
    },
}

FEDERAL_PUBLISHERS = {
    "bea",
    "bls",
    "bts",
    "census",
    "cbo",
    "dol-eta",
    "eia",
    "fdic",
    "federal-reserve-board",
    "federal-reserve-bank-of-new-york",
    "philadelphia-fed",
    "chicago-fed",
    "atlanta-fed",
    "cleveland-fed",
    "st-louis-fed",
    "us-treasury",
}

RESTRICTED_PUBLISHERS = {
    "moodys",
    "ice-bofa",
    "sp-corelogic",
    "sp-dow-jones",
    "nasdaq",
    "cboe",
    "university-of-michigan",
    "indeed",
}


def parse_tuple_constant(path: Path, names: Set[str]) -> Set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    values: Set[str] = set()
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if not any(isinstance(target, ast.Name) and target.id in names for target in targets):
            continue
        value_node = node.value
        try:
            literal = ast.literal_eval(value_node)
        except (ValueError, TypeError):
            continue
        if isinstance(literal, tuple):
            values.update(item for item in literal if isinstance(item, str))
    return values


def infer_publisher(series_id: str) -> Tuple[str, str]:
    curated = CURATED.get(series_id, {})
    if curated.get("publisher"):
        return curated["publisher"], "curated"
    if re.match(r"^(CES|LNS|LAU|SMS|[A-Z]{2}MFG)", series_id):
        return "bls", "identifier_pattern"
    if re.match(r"^[A-Z]\d{3,}|.*(RC|RX|BEA)", series_id):
        return "bea", "identifier_pattern"
    if series_id.startswith(("DGS", "GS")):
        return "us-treasury", "identifier_pattern"
    return "unknown", "unresolved"


def infer_category(series_id: str) -> Tuple[str, str]:
    curated = CURATED.get(series_id, {})
    if curated.get("category"):
        return curated["category"], "curated"
    if re.search(r"(MFG|MANEMP|PAYEMS|EMP|URN$|NA$)", series_id):
        return "labor_or_spatial_employment", "identifier_pattern"
    if re.search(r"(HPI|HOUSE|HOUST|PERMIT)", series_id):
        return "housing", "identifier_pattern"
    if re.search(r"(GDP|GSP|PI$|INCOME)", series_id):
        return "income_or_output", "identifier_pattern"
    if re.search(r"(RATE|UEMP|UNRATE)", series_id):
        return "labor_unemployment", "identifier_pattern"
    return "unclassified_quantitative", "unresolved"


def provider_for(series_id: str, publisher: str) -> Tuple[str, str]:
    if series_id in {
        "ADS_INDEX",
        "CLEVELAND_INFLATION_NOWCAST_Q",
        "SPF_MEDIAN_RGDP_LEVEL",
        "SPF_MEDIAN_UNEMP_LEVEL",
        "anxious_index",
        "nyfed_recession_prob",
        "fdic_failures_by_year",
    }:
        return publisher, ""
    return "fred", f"https://fred.stlouisfed.org/series/{series_id}"


def coverage_status(first: str, last: str) -> str:
    if not first or not last:
        return "unknown_unparsed"
    if last < "1950-01-01":
        return "ends_before_1950"
    if first <= "1950-01-01":
        return "covers_1950"
    return "starts_after_1950_source_or_local_limit"


def rights_status(publisher: str) -> str:
    if publisher in FEDERAL_PUBLISHERS:
        return "public_source_reuse_terms_and_attribution_review_required"
    if publisher in RESTRICTED_PUBLISHERS:
        return "restricted_or_licensing_review_required"
    return "source_specific_rights_review_required"


def revision_class(series_id: str, vintage_count: int, publisher: str) -> str:
    if vintage_count:
        return "revising_local_vintages_retained"
    if publisher in {"bea", "bls", "census", "federal-reserve-board"}:
        return "likely_revising_needs_series_confirmation"
    if series_id.startswith(("DGS", "DEX")):
        return "market_observation_generally_nonrevising_corrections_possible"
    return "unresolved"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
    )
    args = parser.parse_args()
    root = args.root.resolve()
    local_path = root / "data_vault/catalog/local_series_inventory.csv"
    with local_path.open("r", encoding="utf-8", newline="") as handle:
        local_rows = list(csv.DictReader(handle))

    production = parse_tuple_constant(
        root / "method_source/production_sources.py",
        {"NATIONAL_SERIES", "INDUSTRY_SERIES", "AUXILIARY_SERIES"},
    )
    task3_sources = set(
        json.loads((root / "method_source/bhi2_sources.json").read_text())["sources"]
    )

    # B-META-1: seasonal-adjustment status landed from FRED fred/series metadata.
    # The catalog field carries the FRED short code (SA|NSA|SAAR|SSA); series FRED
    # does not serve, and every non-FRED source, remain an honest 'unresolved'.
    sa_meta = json.loads(
        (root / "data_vault/catalog/fred_series_metadata.v1.json").read_text()
    )["series"]

    output_rows: List[Dict[str, object]] = []
    for local in local_rows:
        series_id = local["series_id"]
        curated = CURATED.get(series_id, {})
        publisher, publisher_basis = infer_publisher(series_id)
        category, category_basis = infer_category(series_id)
        provider, provider_url = provider_for(series_id, publisher)
        frequency = curated.get("frequency", "unresolved")
        vintage_count = int(local["vintage_file_count"])
        lanes = json.loads(local["lanes_json"])
        parse_statuses = json.loads(local["parse_statuses_json"])
        strict = (
            "candidate_not_proven"
            if "publisher_release_candidate" in lanes
            else "not_proven_from_provider_snapshots"
            if vintage_count
            else "not_locally_supported"
        )
        sa_short = sa_meta.get(series_id, {}).get("seasonal_adjustment_short") or "unresolved"
        confidence_parts = {
            publisher_basis,
            category_basis,
            "curated_frequency" if frequency != "unresolved" else "frequency_unresolved",
            "seasonal_adjustment_fred_landed"
            if sa_short != "unresolved"
            else "seasonal_adjustment_unresolved",
        }
        output_rows.append(
            {
                "schema_version": SCHEMA_VERSION,
                "series_id": series_id,
                "title": curated.get("title", series_id),
                "category": category,
                "publisher": publisher,
                "provider": provider,
                "provider_series_id": series_id,
                "provider_landing_url": provider_url,
                "observation_frequency": frequency,
                "frequency_evidence": (
                    "curated_local_and_source_review"
                    if frequency != "unresolved"
                    else "unresolved"
                ),
                "units": curated.get("units", "unresolved"),
                "seasonal_adjustment": sa_short,
                "local_first_observation": local["first_observation_date"],
                "local_last_observation": local["last_observation_date"],
                "local_1950_coverage_status": coverage_status(
                    local["first_observation_date"], local["last_observation_date"]
                ),
                "local_file_count": local["file_count"],
                "local_current_file_count": local["current_file_count"],
                "local_vintage_file_count": local["vintage_file_count"],
                "local_first_vintage": local["first_vintage_date"],
                "local_last_vintage": local["last_vintage_date"],
                "local_lanes_json": json.dumps(lanes, separators=(",", ":")),
                "parse_statuses_json": json.dumps(parse_statuses, separators=(",", ":")),
                "original_production_input": str(series_id in production).lower(),
                "task3_governed_input": str(series_id in task3_sources).lower(),
                "forecast_or_nowcast": str(category in {"forecast", "reference_model"}).lower(),
                "revision_class": revision_class(series_id, vintage_count, publisher),
                "named_vintage_local_status": (
                    "retained_provider_snapshots_not_yet_release_proof"
                    if vintage_count
                    else "not_locally_retained"
                ),
                "strict_first_release_local_status": strict,
                "release_clock_status": "exact_release_event_ledger_pending",
                "rights_status": curated.get(
                    "rights_status", rights_status(publisher)
                ),
                "metadata_confidence": "|".join(sorted(confidence_parts)),
                "notes": " | ".join(filter(None, (
                    curated.get("notes", ""),
                    "HTML/empty/error content present; inspect anomaly manifest"
                    if any(
                        value in {"html_masquerading_as_csv", "empty_file"}
                        or value.startswith("csv_error:")
                        for value in parse_statuses
                    )
                    else "",
                ))),
            }
        )

    output_path = root / "data_vault/catalog/metric_catalog.csv"
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(output_rows)
    print(
        json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                "rows": len(output_rows),
                "curated_rows": sum(row["series_id"] in CURATED for row in output_rows),
                "production_rows": sum(row["series_id"] in production for row in output_rows),
                "task3_rows": sum(row["series_id"] in task3_sources for row in output_rows),
                "vintage_rows": sum(int(row["local_vintage_file_count"]) > 0 for row in output_rows),
                "output": output_path.relative_to(root).as_posix(),
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
